meta:
  schema-version: 0.1.0
  created-on: "2024-03-22T23:57:17Z"
  cli-version: 0.2.0
projects:
  securitiai-gravity-web-package-lock.json:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      minimist:
        1.2.0:
          use: 1.2.0-sp1
        0.0.8:
          use: 0.0.8-sp1
      y18n:
        4.0.0:
          use: 4.0.0-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
      acorn:
        5.7.3:
          use: 5.7.3-sp1
      json5:
        1.0.1:
          use: 1.0.1-sp1
        2.1.0:
          use: 2.1.0-sp1
        0.5.1:
          use: 0.5.1-sp1
      ip:
        1.1.5:
          use: 1.1.5-sp1
      qs:
        6.7.0:
          use: 6.7.0-sp1
        6.5.2:
          use: 6.5.2-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      handlebars:
        4.1.2:
          use: 4.1.2-sp1
      json-schema:
        0.2.3:
          use: 0.2.3-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      lodash:
        4.17.15:
          use: 4.17.15-sp1
      ansi-regex:
        4.1.0:
          use: 4.1.0-sp1
        3.0.0:
          use: 3.0.0-sp1
      loader-utils:
        0.2.17:
          use: 0.2.17-sp1
        1.2.3:
          use: 1.2.3-sp2
      tough-cookie:
        2.5.0:
          use: 2.5.0-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
